### PR TITLE
Remove mask

### PR DESCRIPTION
**Pull request by abaliunov-sc**

### CODE REVIEW

**Comment by abaliunov-sc** [comment]
[demo.tar.gz](https://github.com/OpusCapita/react-dates/files/1303045/demo.tar.gz)

**Comment by asergeev-sc** [comment]
Setup online site that provides working UI for the pull request. So QA could test it. If fixes are required, then developer makes changes, and online version is updated again...

**Comment by kvolkovich-sc** [comment]
See demo here. https://opuscapita.github.io/react-dates/branches/removeMask/

**Comment by kvolkovich-sc** [comment]
1. Remove outline around input
2. Make background `transparent` if input disabled

dates

**Comment by nstoliar-sc** [comment]
Dates in dateinputs are displayed on appropriate set format. Please, fix dateinput styles.

**Comment by abaliunov-sc** [comment]
Done
[See](https://opuscapita.github.io/react-dates//branches/removeMask/?currentComponentId=%40opuscapita%2Freact-dates%2F0.3.0-beta.14%2FDateRangeInput&maxContainerWidth=31%25&showSidebar=false)

**Pull request merged**
